---
name: Bug Report
about: Create a report to help us improve the Meal Generator Planner
title: '[BUG] '
labels: ['bug']
assignees: ''
---

## Bug Description
A clear and concise description of what the bug is.

## Steps to Reproduce
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

## Expected Behavior
A clear and concise description of what you expected to happen.

## Actual Behavior
A clear and concise description of what actually happened.

## Screenshots
If applicable, add screenshots to help explain your problem.

## Environment
- Platform: [e.g., Android, iOS, Web]
- Device: [e.g., iPhone 12, Samsung Galaxy S21, Desktop Chrome]
- OS Version: [e.g., iOS 15.0, Android 12, Windows 11]
- App Version: [e.g., 1.0.0]

## Flutter Doctor Output
If reporting a development issue, please include the output of `flutter doctor -v`

## Additional Context
Add any other context about the problem here.